import 'bootstrap/dist/css/bootstrap.min.css';
import "../src/asset/css/customCss.css"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
