import 'bootstrap/dist/css/bootstrap.min.css';
import "../src/asset/css/customCss.css"
import {Poppins,Outfit} from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
})
const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${outfit.variable} ${poppins.variable}`}>
      <body >{children}</body>
    </html>
  );
}
